version: '2'
services:
  rcapplication-app:
    image: rcapplication
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mariadb://rcapplication-mariadb:3306/rcapplication
      - JHIPSTER_SLEEP=120 # gives time for mariadb server to start
    ports:
      - 8080:8080
  rcapplication-mariadb:
    extends:
      file: mariadb.yml
      service: rcapplication-mariadb
